### ISSUE TITLE
translation not working

### ISSUE THREAD

**Issue by nimafanniasl** [dusansimic/dynamic-wallpaper#14]
Hi!
FA translation is Not woking

even with "flatpak config --set languages 'fa'"

**Comment by dusansimic** [comment]
Hi! The lang name for Persian is `fa_IR.UTF-8` if I'm not wrong. You should be able to change the locale with either `localectl` command or in the graphical settings of your desktop environment.

**Comment by nimafanniasl** [comment]
.

**Comment by nimafanniasl** [comment]
Can You Please Sen a Picture Of That? All Texts Are English!

**Comment by dusansimic** [comment]
![image](https://user-images.githubusercontent.com/12685466/167904561-d5e3e360-b121-4fdc-a680-a0ba3e1fe98d.png)

**Comment by nimafanniasl** [comment]
Wow! How????
That's not working for me:
![image](https://user-images.githubusercontent.com/76901932/167911668-de57ba5a-2e64-4b4a-af79-02e5df2f20a8.png)

**Comment by nimafanniasl** [comment]
My Friends Tested This Too, Not Working For Them

**Comment by nimafanniasl** [comment]
(process:2): Gtk-WARNING **: 22:12:54.458: Locale not supported by C library.
	Using the fallback 'C' locale.
