### ISSUE TITLE
Translations are out of date

### ISSUE THREAD

**Issue by dusansimic** [dusansimic/dynamic-wallpaper#34]
The translation template is updated so translations are out of date.

- [x] Turkish (@libreajans)
- [x] French (@rene-coty)
- [x] Czech (@vikdevelop)
- [x] Russian (@daudix-UFO)
- [x] Spanish (@TWB0109)
- [x] Persian (@nimafanniasl)
- [x] Occitan (@Mejans)
- [x] Brazillian Portuguese (@pesader)
- [x] Dutch (@Vistaus)
- [x] Italian (@musiclover382)

**Comment by nextdoorpanda** [comment]
Hi! Would you be interested in a Greek translation? :)

**Comment by nimafanniasl** [comment]
Hi! Let me check :)

**Comment by dusansimic** [comment]
@nextdoorpanda of course! Feel free to send a pull request! Also if you're interested and if you're not already participating, check out [Hacktoberfest](https://hacktoberfest.com/) 😁.

**Comment by musiclover382** [comment]
@dusansimic Just wanted to thank you for notifying us, it's much easier for us to keep the extensions updated!!

**Comment by nextdoorpanda** [comment]
@dusansimic Thank you! 😀 This is my second hacktoberfest! 😆

**Comment by libreajans** [comment]
Turkish translation updated: https://github.com/dusansimic/dynamic-wallpaper/pull/38

@dusansimic 

Is there any reason to stay on GNOME runtime 42?

https://github.com/dusansimic/dynamic-wallpaper/blob/main/me.dusansimic.DynamicWallpaper.json#L4

**Comment by dusansimic** [comment]
@libreajans none whatsoever :) I'll bump it either today or tomorrow and probably push a new release once all translations are in.

**Comment by daudix-UFO** [comment]
Russian translation updated: #40

**Comment by dusansimic** [comment]
@daudix-UFO Fantastic! Great to have you here 😁.
