### ISSUE TITLE
Rewrite ui files to Blueprint templates

### ISSUE THREAD

**Issue by dusansimic** [dusansimic/dynamic-wallpaper#42]
Since [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) is quite stable now and we have everything we need from it, ui files could be rewritten in Blueprint. It's much easier to read, write and maintain the templates then.

**Comment by 0xMRTT** [comment]
Hi,

If you are okay, i'll be glad to work on that!

**Comment by dusansimic** [comment]
Of course! Feel free to send a pr 😁!

**Comment by dusansimic** [comment]
> So, you can add hacktobearfest-accepted label ?

No need :) This repo already has the hacktoberfest label which qualifies every pr sent to it for hacktoberfest.

**Comment by 0xMRTT** [comment]
#55
