### ISSUE TITLE
Make a list of translators

### ISSUE THREAD

**Issue by dusansimic** [dusansimic/dynamic-wallpaper#44]
In order to more easily track translators and who to notify once the translation template is changed, there could be a `TRANSLATORS.md` file which would contain all translators and their profiles for each language that is supported. I could be just a list of languages and next to it tags to profiles of those translators.

**Comment by Abhay5855** [comment]
Hey @dusansimic  can you assign me this issue please

**Comment by dusansimic** [comment]
Feel free to work on this issue in a draft PR and make it a regular PR once you're done :)

**Comment by Abhay5855** [comment]
yes sure @dusansimic
