### ISSUE TITLE
Update screenshots before next release

### ISSUE THREAD

**Issue by dusansimic** [dusansimic/dynamic-wallpaper#49]
Since ui was redesigned in #31, the screenshots are outdated. The screenshots should represent current ui of the app so they should be updated.

**Comment by Conor0Callaghan** [comment]
I'm happy to have a look at this @dusansimic do you just want them updated on the README?

**Comment by dusansimic** [comment]
They are stored in `data/screenshots` so it should be fine to update them just there (replace the old files with new ones). You can just use the GNOMEs integrated window screenshot tool. Once files are replaced, the readme will be updated as well as screenshots on Flathub.
