### ISSUE TITLE
Flatpak does not seem to work

### ISSUE THREAD

**Issue by pesader** [dusansimic/dynamic-wallpaper#5]
Hi! I was excited to try out Dynamic Wallpaper on my machine, now that the flatpak is available on Flathub, however I did not seem to work. I was able to select pictures for the light and dark wallpaper variants, and got a toast saying the wallpaper was created but it was nowhere to be found on GNOME Settings' Appearance tab.

Also, when I tried creating another wallpaper with the same name, I got a warning saying that was not possible (so it must be running up until the point it "registers" the new wallpaper).

Lastly, thanks for developing this great application (it was exactly what I was looking for)! ☀️ 🌑

**Comment by Ardelean-Calin** [comment]
I think I found the issue. On my machine, the folder `gnome-background-properties` found in `$HOME/.local/share` did not exist. The flatpak application [tries to create the directory](https://github.com/dusansimic/dynamic-wallpaper/blob/02c56036b9e8e4349e79131f23fa01127e2c6e9e/src/window.py#L87) but for some reason it fails. I'm guessing it doesn't have the right permissions to create directories. Weird enough, it **does** have the right permissions to copy the images in the `backgrounds` directory.
